name: "AS-Test"
description: "My first real add-on!"
version: "1.1.0"
slug: "hello_world AS-Test"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
